default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: ":rotating_light: auto fix by pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: master
  autoupdate_schedule: monthly
  autoupdate_commit_msg: ":arrow_up: auto update by pre-commit hooks"
repos:
  - repo: local
    hooks:
      - id: generate-client-pyi
        name: generate client.pyi
        entry: scripts/generate_client_pyi.py
        language: python
        additional_dependencies:
          - loguru>=0.7.3
          - rich>=14.3.3
          - richuru>=0.1.1
        pass_filenames: false
        files: ^(nonebot/adapters/discord/api/handle\.py|scripts/generate_client_pyi\.py)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [pre-commit]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/nonebot/nonemoji
    rev: v0.1.4
    hooks:
      - id: nonemoji
        stages: [prepare-commit-msg]
